CREATE OR REPLACE PROCEDURE insertDBUSER(
	   p_userid IN DBUSER.USER_ID%TYPE,
	   p_username IN DBUSER.USERNAME%TYPE,
	   p_createdby IN DBUSER.CREATED_BY%TYPE,
	   p_date IN DBUSER.CREATED_DATE%TYPE)
IS
BEGIN

  INSERT INTO DBUSER ("USER_ID", "USERNAME", "CREATED_BY", "CREATED_DATE")
  VALUES (p_userid, p_username,p_createdby, p_date);

  COMMIT;

END;
/



CREATE TABLE SMET_MODULI_OBUKA
  (	"ID" NUMBER(32,0) NOT NULL ENABLE, 
	"SIFRA" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"OZNAKA" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"NAZIV" VARCHAR2(240 BYTE), 
	 CONSTRAINT "METMODOBUKA_PK" PRIMARY KEY ("ID")
);
 

CREATE OR REPLACE TRIGGER BIR_SMET_MODULI_OBUKA
 BEFORE INSERT
 ON smet_moduli_obuka
 FOR EACH ROW
BEGIN
  :NEW.id := pra_zmp_zaj.i3_sekvenca (:NEW.id);
  :NEW.sifra := UPPER (:NEW.sifra);
END BIR_smet_moduli_obuka;
/

ALTER TRIGGER BIR_SMET_MODULI_OBUKA ENABLE;
 


