package hr.istratech.prevodenje;

/**
 * Created by dbursic on 5.10.2017..
 */
public enum ExampleType {
    FORM_NAME_CHANGER, FORM_NAME_PRINTER, FORM_NAME_SAVER, FORM_CODE_PRINTER, FORM_PROPERTIES_PRINTER,
    REPORT_REX_GENERATOR, REPORT_LABEL_EXTRACTOR, REPORT_EXTRACT_MESSAGES
}
